name: sportcon_1st_gui
description: "A sports connection platform for players, coaches, and field renters"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State management
  provider: ^6.1.1
  
  # Network and API
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  
  # UI components
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  flutter_rating_bar: ^4.0.1
  
  # Location services
  geolocator: ^10.1.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    # You can add additional asset folders here