# Generated by Django 5.2 on 2025-04-27 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsfields',
            name='renter_id',
            field=models.ForeignKey(db_column='renter_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.renters'),
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.users')),
            ],
        ),
    ]
