# Generated by Django 5.2 on 2025-04-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sportsfields_renter_id_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsfields',
            name='renter_id',
            field=models.ForeignKey(blank=True, db_column='renter_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.renters'),
        ),
    ]
