# Generated by Django 5.2 on 2025-04-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sportsfields_renter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='team1_id',
            field=models.ForeignKey(blank=True, db_column='team1_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='api.teams'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team2_id',
            field=models.ForeignKey(blank=True, db_column='team2_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='api.teams'),
        ),
        migrations.AlterField(
            model_name='sportsfields',
            name='renter_id',
            field=models.ForeignKey(blank=True, db_column='renter_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.renters'),
        ),
    ]
